---
- hosts: all
  become: true
  tasks:
  - name: ensure nginx is at the latest version
    apt: name=nginx state=latest
  - name: start nginx
    service:
      name: nginx
      state: started
      enabled: true
  - name: copy website
    copy:
      src: index.html
      dest: /var/www/html/index.html
      mode: 0644
